version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data

  auth_service:
    build: .
    container_name: auth_service
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pg_data:
